#!/usr/bin/env python3
"""RO-Crate 1.3 metadata export for auto-doc-engine research artifacts.

This module writes the core RO-Crate JSON-LD structure for a directory of
payload files. It intentionally stays stdlib-only and conservative:

- ``ro-crate-metadata.json`` is the metadata descriptor;
- the crate root is a ``Dataset``;
- payloads are ``File`` data entities;
- authors are contextual ``Person`` entities;
- file identity evidence is represented with Schema.org ``PropertyValue``
  entities carrying SHA-256 digests.

Target: RO-Crate 1.3, released 2026-06-22 and listed by the RO-Crate project as
the current long-term release.

Boundary: this is an implementation of the repository's export profile, not a
claim that every generated crate has been checked by an external RO-Crate
validator or that a digest proves scientific correctness.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import sys
from pathlib import Path
from typing import Iterable, List, Optional, Sequence

RO_CRATE_CONTEXT = "https://w3id.org/ro/crate/1.3/context"
RO_CRATE_SPEC = "https://w3id.org/ro/crate/1.3"
METADATA_FILE = "ro-crate-metadata.json"
PROFILE = "auto-doc-engine/ro-crate@1"


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    """Return a hexadecimal SHA-256 digest for ``path``."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(chunk_size)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def _relative_payload(root: Path, path: Path) -> tuple[Path, str]:
    resolved_root = root.resolve()
    resolved_path = path.resolve()
    try:
        relative = resolved_path.relative_to(resolved_root)
    except ValueError as exc:
        raise ValueError(f"payload must be inside crate root: {path}") from exc
    if not resolved_path.is_file():
        raise ValueError(f"payload is not a file: {path}")
    if relative.as_posix() == METADATA_FILE:
        raise ValueError(f"{METADATA_FILE} is generated metadata, not payload")
    return resolved_path, relative.as_posix()


def _person_id(name: str) -> str:
    digest = hashlib.sha256(name.strip().encode("utf-8")).hexdigest()[:12]
    return f"#person-{digest}"


def build_ro_crate(
    root: str | Path,
    payloads: Iterable[str | Path],
    *,
    name: str,
    description: str,
    authors: Optional[Sequence[str]] = None,
    license_value: Optional[str] = None,
) -> dict:
    """Build a compact RO-Crate 1.3 JSON-LD metadata document.

    ``payloads`` may be absolute paths or paths relative to ``root``. Every
    payload must resolve inside the crate root so emitted ``@id`` values remain
    valid local data-entity references.
    """
    root_path = Path(root)
    if not root_path.is_dir():
        raise ValueError(f"crate root is not a directory: {root}")
    if not name.strip():
        raise ValueError("crate name must be non-empty")
    if not description.strip():
        raise ValueError("crate description must be non-empty")

    normalized: List[tuple[Path, str]] = []
    seen = set()
    for item in payloads:
        candidate = Path(item)
        if not candidate.is_absolute():
            candidate = root_path / candidate
        resolved, relative = _relative_payload(root_path, candidate)
        if relative not in seen:
            normalized.append((resolved, relative))
            seen.add(relative)
    normalized.sort(key=lambda item: item[1])

    author_names = [a.strip() for a in (authors or []) if str(a).strip()]
    author_refs = [{"@id": _person_id(author)} for author in author_names]

    root_entity = {
        "@id": "./",
        "@type": "Dataset",
        "name": name.strip(),
        "description": description.strip(),
        "hasPart": [{"@id": relative} for _, relative in normalized],
    }
    if author_refs:
        root_entity["author"] = author_refs
    if license_value and license_value.strip():
        root_entity["license"] = license_value.strip()

    graph: List[dict] = [
        {
            "@id": METADATA_FILE,
            "@type": "CreativeWork",
            "description": "RO-Crate Metadata Descriptor generated by auto-doc-engine",
            "conformsTo": {"@id": RO_CRATE_SPEC},
            "about": {"@id": "./"},
        },
        root_entity,
    ]

    for author in author_names:
        graph.append({"@id": _person_id(author), "@type": "Person", "name": author})

    for path, relative in normalized:
        digest = sha256_file(path)
        digest_id = f"#sha256-{digest}"
        media_type = mimetypes.guess_type(relative)[0] or "application/octet-stream"
        graph.append(
            {
                "@id": relative,
                "@type": "File",
                "name": path.name,
                "contentSize": str(path.stat().st_size),
                "encodingFormat": media_type,
                "identifier": {"@id": digest_id},
            }
        )
        graph.append(
            {
                "@id": digest_id,
                "@type": "PropertyValue",
                "name": "SHA-256",
                "propertyID": "sha256",
                "value": digest,
            }
        )

    return {
        "@context": RO_CRATE_CONTEXT,
        "@graph": graph,
        "profile": PROFILE,
    }


def write_ro_crate(
    root: str | Path,
    payloads: Iterable[str | Path],
    *,
    name: str,
    description: str,
    authors: Optional[Sequence[str]] = None,
    license_value: Optional[str] = None,
    output: Optional[str | Path] = None,
) -> Path:
    """Write RO-Crate metadata and return the output path."""
    root_path = Path(root)
    payload = build_ro_crate(
        root_path,
        payloads,
        name=name,
        description=description,
        authors=authors,
        license_value=license_value,
    )
    output_path = Path(output) if output else root_path / METADATA_FILE
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return output_path


def _discover(root: Path) -> List[Path]:
    """Discover regular payload files below ``root`` excluding generated metadata."""
    ignored_dirs = {".git", "__pycache__", ".pytest_cache"}
    payloads: List[Path] = []
    for path in sorted(root.rglob("*")):
        if any(part in ignored_dirs for part in path.parts):
            continue
        if path.is_file() and path.name != METADATA_FILE:
            payloads.append(path)
    return payloads


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Write RO-Crate 1.3 metadata for research artifacts")
    parser.add_argument("root", help="RO-Crate root directory")
    parser.add_argument("payload", nargs="*", help="payload files relative to the crate root")
    parser.add_argument("--all-files", action="store_true", help="include all regular files under the crate root")
    parser.add_argument("--name", required=True, help="human-readable crate name")
    parser.add_argument("--description", required=True, help="human-readable crate description")
    parser.add_argument("--author", action="append", default=[], help="author name; may be repeated")
    parser.add_argument("--license", dest="license_value", help="license identifier or URL")
    parser.add_argument("--output", help="metadata output path; defaults to <root>/ro-crate-metadata.json")
    args = parser.parse_args(argv)

    root = Path(args.root)
    if not root.is_dir():
        print(f"ro-crate: root directory not found: {root}", file=sys.stderr)
        return 2
    payloads: Iterable[str | Path]
    if args.all_files:
        payloads = _discover(root)
    else:
        if not args.payload:
            print("ro-crate: provide payload files or --all-files", file=sys.stderr)
            return 2
        payloads = args.payload

    try:
        output = write_ro_crate(
            root,
            payloads,
            name=args.name,
            description=args.description,
            authors=args.author,
            license_value=args.license_value,
            output=args.output,
        )
    except (OSError, ValueError) as exc:
        print(f"ro-crate: {exc}", file=sys.stderr)
        return 1
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
